execute pathogen#infect()

"syntax stuff
syntax on
set showmatch
set wildmode=longest,list

"tabs
filetype plugin indent on
set tabstop=3
set shiftwidth=3
set expandtab

"allow these keys to be free!!
set backspace=indent,eol,start

"colorscheme
set background=dark
set colorcolumn=85

"go stuff
let g:go_fmt_command = "goimports"
set rtp+=$GOPATH/src/github.com/golang/lint/misc/vim

"menu options
set wildmenu
set hlsearch
set ruler
set confirm
set cmdheight=1

"searching options
set ignorecase
set smartcase

"beeps!
set visualbell

" to make terminal work
set ma
