"syntax stuff
syntax on
set showmatch
set wildmode=longest,list

"tabs
set tabstop=3
set shiftwidth=3
set expandtab

"allow these keys to be free!!
set backspace=indent,eol,start

"colorscheme
set background=dark
colorscheme molokai
set colorcolumn=85

"go stuff
let g:go_fmt_command = "goimports"
set rtp+=$GOPATH/src/github.com/golang/lint/misc/vim

"menu options
set wildmenu
set hlsearch
set ruler
set confirm
set cmdheight=1

set laststatus=2
set statusline=
set statusline+=%<\                       " cut at start
set statusline+=%2*[%n%H%M%R%W]%*\        " flags and buf no
set statusline+=%-40f\                    " path
set statusline+=%=%1*%y%*%*\              " file type
set statusline+=%10((%l,%c)%)\            " line and column
set statusline+=%P                        " percentage of file

"searching options
set ignorecase
set smartcase

"beeps!
set visualbell

" to make terminal work
set ma
