# so "ls" output doesn't look crazy
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

# stuff to make tmux colors happy
export CLICOLOR=1
export TERM=xterm-256color

# set default editor to be vim
export EDITOR=vim

# go stuff
export GOPATH=/Users/ren/workspace/go
export GOBIN=$GOPATH/bin

alias ll='ls -lG'

# https://github.com/jonmosco/kube-ps1
export KUBE_PS1_CTX_COLOR="cyan"
export KUBE_PS1_PREFIX="["
export KUBE_PS1_SUFFIX="] "
export KUBE_PS1_NS_ENABLE="false"
export KUBE_PS1_SYMBOL_ENABLE="false"
source "/usr/local/opt/kube-ps1/share/kube-ps1.sh"
export PROMPT="$(whoami)@$(scutil --get ComputerName) → "
PROMPT='$(kube_ps1)'$PROMPT

# https://git-scm.com/book/en/v2/Appendix-A%3A-Git-in-Other-Environments-Git-in-Zsh
autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
RPROMPT=\$vcs_info_msg_0_
zstyle ':vcs_info:git:*' formats '%b'

# kubectl alias
alias e='vim'
alias k='kubectl'
alias kgp='kubectl get po'
alias kgs='kubectl get sts'
alias kga='kubectl get all'
alias kgsv='kubectl get svc'
alias kgpvc='kubectl get pvc'
alias kgpv='kubectl get pv'
alias kgn='kubectl get node'
alias ksc='kubectl scale'
alias kd='kubectl describe'
alias krm='kubectl delete'
alias ke='kubectl edit'
alias kprod='kubectl --context cv-prod-useast-1'
alias kstg='kubectl --context cv-staging'

bindkey -e
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word

# gpg
export GPG_TTY=$(tty)
