export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
export CLICOLOR=1
export TERM=xterm-256color
export EDITOR=nvim
export GOPATH=/Users/ren/go
export GOBIN=/Users/ren/go/bin

alias ll='ls -lG'
alias vim='nvim'

# kube-ps1 https://github.com/jonmosco/kube-ps1
export KUBE_PS1_SYMBOL_COLOR="${KUBE_PS1_SYMBOL_COLOR-blue}"
export KUBE_PS1_CTX_COLOR="${KUBE_PS1_CTX_COLOR-cyan}"
export KUBE_PS1_NS_COLOR="${KUBE_PS1_NS_COLOR-magenta}"
source "/usr/local/opt/kube-ps1/share/kube-ps1.sh"
PS1='$(kube_ps1)'$PS1


alias k='kubectl'
alias kp='kubectl get po'
alias ks='kubectl get sts'
alias ka='kubectl get all'
alias ksv='kubectl get svc'
alias kpvc='kubectl get pvc'
alias kpv='kubectl get pv'
alias kn='kubectl get node'
alias kd='kubectl describe'
alias krm='kubectl delete'
alias ke='kubectl edit'

bindkey -e
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/ren/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/ren/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/ren/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/ren/google-cloud-sdk/completion.zsh.inc'; fi
