# so "ls" output doesn't look crazy
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

# stuff to make tmux colors happy
export CLICOLOR=1
export TERM=xterm-256color

# set default editor to be vim
export EDITOR=vim

# go stuff
export GOPATH=/Users/ren/workspace/go
export GOBIN=$GOPATH/bin

alias ll='ls -lG'

# https://github.com/jonmosco/kube-ps1
export KUBE_PS1_CTX_COLOR="cyan"
export KUBE_PS1_PREFIX="["
export KUBE_PS1_SUFFIX="] "
export KUBE_PS1_NS_ENABLE="false"
export KUBE_PS1_SYMBOL_ENABLE="false"
source "/usr/local/opt/kube-ps1/share/kube-ps1.sh"
export PROMPT="$(whoami)@$(scutil --get ComputerName) → "
PROMPT='$(kube_ps1)'$PROMPT

# https://git-scm.com/book/en/v2/Appendix-A%3A-Git-in-Other-Environments-Git-in-Zsh
autoload -Uz vcs_info
zstyle ':vcs_info:*' formats '[%b]'
zstyle ':vcs_info:*' actionformats '(%s)-[%b|%a]'
precmd () {
    psvar=()
    LANG=en_US.UTF-8 vcs_info
    [[ -n "$vcs_info_msg_0_" ]] && psvar[1]="$vcs_info_msg_0_"

    topdir=`git rev-parse --show-toplevel 2>/dev/null`
    if [ $? -eq 0 ]
    then
        stashes=$(git stash list 2>/dev/null | wc -l)
        if [ ${stashes} -eq 0 ]
        then
            psvar[2]=""
        else
            psvar[2]=" @${stashes// /}"
        fi
    fi
}
_DIRPART=%B%{$fg[cyan]%}'[%(5~,%-2~/.../%2~,%~)]'%{$reset_color%}%b
RPROMPT=%B"%1(v|%F{magenta}%1v%f%F{yellow}%2v%f|)"%b${_DIRPART}


# kubectl alias
alias e='vim'
alias k='kubectl'
alias kgp='kubectl get po'
alias kgs='kubectl get sts'
alias kga='kubectl get all'
alias kgsv='kubectl get svc'
alias kgpvc='kubectl get pvc'
alias kgpv='kubectl get pv'
alias kgn='kubectl get node'
alias ksc='kubectl scale'
alias kd='kubectl describe'
alias krm='kubectl delete'
alias ke='kubectl edit'
alias kprod='kubectl --context cv-prod-useast-1'
alias kstg='kubectl --context cv-staging'

bindkey -e
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word

# gpg
export GPG_TTY=$(tty)

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/ren/workspace/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/ren/workspace/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/ren/workspace/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/ren/workspace/google-cloud-sdk/completion.zsh.inc'; fi
